mybatis:
  mapper-locations: mapper/*.xml
  configuration:
    default-statement-timeout: 5
spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/kq?characterEncoding=utf-8
    url: jdbc:mysql://localhost:3306/kq?serverTimezone=UTC
    username: root
    password: root123
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp



human:
  name: 张三
  sex: 男
  age: 13
